### ISSUE TITLE
Occulus rift and htmlmixer

### ISSUE THREAD

**Issue by trakers33** [jeromeetienne/threex.htmlmixer#2]
Salut,

J'ai l'impression que htmlmixer ne supporte pas l'utilisation du mode oculusRift de three.js.

Aurrais-tu une solution ?

Cordialement.

PS: Beau boulot sur tes modules THREEx ;)

**Comment by jeromeetienne** [comment]
sorry about the delay to answer. i just saw your message. 

you are correct htmlmixer isnt compatible with occulusdrift. It is because htmlmixer relies on [css 3d transformations](https://developer.mozilla.org/en-US/docs/Web/Guide/CSS/Using_CSS_transforms) and those arent deformed for the occulus drift.

When you are using the occulus drift, the display needs to deformed in a very specific way. and css3d dosnt provide that.

ps: if i fails to answer in time again, just ping me dont hesitate
